---
services:
  stream-stats:
    build: .
    container_name: stream-stats
    restart: unless-stopped
    ports:
      - "9300:8000"
    volumes:
      - .env:/app/github-readme-streak-stats/.env:ro
    environment:
      TZ: "Asia/Tokyo"
